# DATASCI 185 · Quiz 2 复习 Cheat Sheet

根据 Quiz 2 practice A–F 和 Lecture 5–8 整理；这是复习材料，不代表正式考试的完整范围或资料使用规定。

## 快速查找：有思路，不知道怎么写？

| 我想做什么 | 找哪一节 | 核心写法 |
|---|---|---|
| 随机抽取，不能重复 | 1 | `random.sample(items, k=3)` |
| 再次得到相同随机结果 | 1 | 重新 `random.seed(1337)` |
| 按类别和数值分情况 | 2 | 嵌套 `if / elif / else` |
| 从名称找位置，再读另一个列表 | 3 | `i = names.index(name)` |
| tuple 能不能修改 | 4 | 不能 `t[i] = ...`；可以创建新 tuple |
| 遍历元素或位置 | 5 | `for value in items` / `for i in range(len(items))` |
| 累加到超过门槛就停 | 6 | 先累加，再 `if ...: break` |
| 一直随机尝试直到命中若干次 | 7 | `while hits < target:` |
| 按条件收集元素 | 8 | 空列表 + 循环 + `.append()` |
| 去重、添加、安全删除 | 9 | `set()`、`.add()`、先检查再 `.remove()` |
| 数一数每种颜色出现几次 | 10 | `.count()` 或对应位置加 1 |
| 数组切片、独立复制 | 11 | `a[start:stop]`、`.copy()` |
| 重复模拟、估计概率 | 12 | 外层循环 + 每轮重新随机生成 |
| 把变量放进输出句子 | 13 | `print(f"...{variable}...")` |

## 1. 随机抽样与 seed｜Practice A


使用方法：选择安装了 NumPy 的 Python kernel，按顺序运行代码。随机示例每次结果可能不同。代码单元格会复用变量名，建议从上到下运行；文中的预期结果用于对照。


In [1]:
import random

cards = ["A", "2", "3", "4", "5", "6", "7", "8"]

one = random.choice(cards)             # 返回一个元素，例如 "4"
many = random.choices(cards, k=3)       # 返回列表，允许重复
different = random.sample(cards, k=3)  # 返回列表，不放回抽取
die = random.randint(1, 6)             # 整数 1～6，包含 1 和 6


- `choice` 没有 s：一个元素。
- `choices` 有 s：多个，可以重复。
- `sample`：不放回。原列表元素不重复时，抽到的值也不重复；k 不能超过列表长度。
- `random.randint(1, 6)` 包含终点；`range(1, 6)` 不包含终点。

**复现同一次抽样：**


In [3]:
random.seed(1337)
hand1 = random.sample(cards, k=3)

random.seed(1337)
hand2 = random.sample(cards, k=3)

print(hand1 == hand2)  # True


True


seed 重置随机序列的起点。相同 seed 后执行相同抽样步骤，得到相同结果。只设一次 seed、连续抽两次，不保证相同。`random.seed()` 不控制 `np.random`。

## 2. 条件判断：选一个分支，还是分别检查？｜Practice B

**一条 if/elif/else 链，只执行第一个满足条件的分支：**


In [5]:
score = 85

if score >= 90:
    grade = "A"
elif score >= 80:
    grade = "B"
else:
    grade = "Below B"

print(grade)  # B


B


**嵌套：先判断类别，再判断该类别里的数值。嵌套完全可以用！**


In [6]:
category = "student"
age = 20

if category == "student":
    if age < 18:
        price = 5
    else:
        price = 8
else:
    price = 12

print(price)  # 8


8


缩进决定归属：内部的 else 对应 `if age < 18`；最外层 else 对应类别判断。

**你之前踩过的坑：独立 if 覆盖答案。**


In [7]:
temperature = 10

if temperature < 15:
    feels = "cold"
if temperature > 26:
    feels = "hot"
else:
    feels = "just right"

print(feels)  # just right：前面设置的 cold 被覆盖了


just right


这里 else 只属于第二个 if。三个结果是互斥选项时，把第二个 if 改成 elif：


In [ ]:
if temperature < 15:
    feels = "cold"
elif temperature > 26:
    feels = "hot"
else:
    feels = "just right"


**比较与逻辑 syntax：**


In [8]:
x = 8                  # 赋值
print(x == 8)          # True：比较相等
print(x != 8)          # False
print(5 <= x < 10)     # True
print(x > 5 and x < 10)  # True：两个都满足
print(x < 5 or x > 10)   # False：至少一个满足
print(not (x == 8))      # False：取反
print("Amy" < "Ben")    # True：逐字符比较，区分大小写


True
False
True
True
False
False
True


边界词：below `<`；above/exceeds `>`；at least `>=`；at most `<=`。先检查临界值，例如 15、26、48；不要只看一次随机输出。

## 3. Index：从值找位置，从位置取值｜Practice E


In [ ]:
names = ("Amy", "Ben", "Cindy")
scores = [75, 92, 88]

i = names.index("Cindy")
print(i)          # 2
print(names[i])   # Cindy
print(scores[i])  # 88

scores[i] = 95
print(scores)     # [75, 92, 95]


`names.index("Cindy")`：知道名字，查位置。`names[2]`：知道位置，取名字。

同一位置可以连接多个顺序对应的 list/tuple。上面只修改 scores，names 不变。


In [ ]:
print(names[-1])  # Cindy：最后一个
print(names[-2])  # Ben：倒数第二个


`.index()` 返回第一个匹配的位置，找不到会报错；不能用它区分重复值各自的位置。NumPy array 没有列表的 `.index()` 方法。

## 4. Tuple、List、Set：特别复习 tuple


In [ ]:
my_list = ["Amy", "Ben"]
my_tuple = ("Amy", "Ben")
my_set = {"Amy", "Ben"}


| 类型 | 按位置读取 | 修改某个位置 | 重复值 |
|---|---|---|---|
| list | 可以 | 可以 | 保留 |
| tuple | 可以 | 不可以 | 保留 |
| set | 不可以 | 没有位置；可添加删除元素 | 去重 |

**单元素 tuple：关键是逗号。**


In [9]:
a = ("Amy")
b = ("Amy",)

print(type(a))  # <class 'str'>
print(type(b))  # <class 'tuple'>


<class 'str'>
<class 'tuple'>


**tuple 可以读取、找位置、切片、遍历：**


In [10]:
t = ("Amy", "Ben", "Cindy")

print(t[1])            # Ben
print(t.index("Ben"))  # 1
print(t[0:2])          # ('Amy', 'Ben')：不包含位置 2

for name in t:
    print(name)


Ben
1
('Amy', 'Ben')
Amy
Ben
Cindy


切片仍然是 tuple，不会把名字拼接成一个字符串。

**不能改原 tuple 的位置，但可以创建新的 tuple，再赋给变量：**


In [11]:
t = ("Amy", "Ben")
# t[0] = "Cindy"  # TypeError

t = t + ("Cindy",)
print(t)  # ('Amy', 'Ben', 'Cindy')


('Amy', 'Ben', 'Cindy')


`+` 创建了新 tuple；赋值让 t 指向新 tuple。tuple 没有 `.append()`。

**交换：**


In [12]:
a = "left"
b = "right"
a, b = b, a
print(a, b)  # right left


right left


## 5. For：遍历的是值，还是 index？


In [13]:
receipts = [30, 40, 25]

for value in receipts:
    print(value)  # 依次 30、40、25

for i in range(len(receipts)):
    print(i, receipts[i])  # 依次 (0,30)、(1,40)、(2,25)


30
40
25
0 30
1 40
2 25


变量名 i 不会自动表示索引！决定其含义的是 `in` 后面遍历什么。


In [14]:
print(list(range(3)))        # [0, 1, 2]
print(list(range(1, 4)))     # [1, 2, 3]
print(list(range(0, 6, 2)))  # [0, 2, 4]


[0, 1, 2]
[1, 2, 3]
[0, 2, 4]


`range(start, stop, step)` 包含起点、不包含终点。`range(100)` 执行 100 次。

## 6. 累加、计数、break、continue｜Practice C

**累加的是数值；计数加的是 1：**


In [15]:
values = [10, 20, 30]
total = 0
count = 0

for value in values:
    total += value
    count += 1

print(total)  # 60
print(count)  # 3


60
3


初始化在循环外。`total += value` 等价于 `total = total + value`；Python 不用 `count++`。

**先加，再检查是否超过门槛：**


In [16]:
receipts = [30, 40, 25]
total = 0

for receipt_number in range(len(receipts)):
    total += receipts[receipt_number]
    if total > 90:
        break

print(total)  # 95
print(f"stopped at receipt # {receipt_number}")  # 2


95
stopped at receipt # 2


这段适用于题目给定的非空 receipts。没有超过门槛时，会处理到最后一个元素。

**处理 3 张，最后的 index 是 2。** 题目从零编号时，要输出 index，不是数量。超过 90 是 `> 90`，不是 `>= 90`。

**continue：跳过本轮剩余代码，不退出循环。**


In [17]:
values = [2, -3, 5]
total = 0

for value in values:
    if value < 0:
        continue
    total += value

print(total)  # 7


7


break 退出最近一层循环；continue 进入最近一层循环的下一轮。变量别命名为 sum，避免覆盖内置 `sum()`。

## 7. While：直到目标发生才停止｜Practice D

**分别记录总尝试次数与命中次数：**


In [ ]:
import random

num_rolls = 0
hits = 0

while hits < 2:
    roll = random.choice([1, 2, 3, 4, 5, 6])
    num_rolls += 1

    if roll == 3:
        hits += 1

print(num_rolls)


- `num_rolls`：每掷一次都加 1。
- `hits`：只有掷到 3 才加 1。
- 达到第二个 3 后，下次检查 `hits < 2` 为 False，循环停止。
- “累计两次”不要求连续，没掷到 3 时不要把 hits 清零。
- 随机抽取必须在循环里，每轮重新抽。

给定结果 `1, 4, 3, 1, 1, 1, 2, 3`，总次数是 8。

## 8. 筛选元素，放进新列表


In [ ]:
names = ["Amy", "Ben", "Cindy"]
scores = [75, 92, 88]
selected = []

for i in range(len(names)):
    if scores[i] >= 80:
        selected.append(names[i])

print(selected)  # ['Ben', 'Cindy']


`.append(value)` 在列表末尾添加一个元素。


In [ ]:
selected = []
selected = selected + ["Amy"]  # list + list 可以
# selected = selected + "Amy"  # list + string 不可以


也不要写 `selected = selected.append("Amy")`：append 原地修改，返回 None。

## 9. Set：添加、去重、安全删除｜Practice F


In [ ]:
colors = ["red", "red", "blue"]
s = set(colors)
print(len(s))  # 2

empty = set()  # 空集合；{} 是空字典
s.add("green")
s.add("red")  # 已存在，不会重复添加


set 不保证顺序，不能 `s[0]`。

**安全删除多个可能存在的元素：**


In [ ]:
courses = {"MATH 100", "BIOL 101", "CHEM 101"}
courses.add("ART 100")
to_remove = ["MATH 100", "PHYS 100", "CHEM 101"]

for course in to_remove:
    if course in courses:
        courses.remove(course)

print(courses)  # 剩 BIOL 101 和 ART 100，顺序不保证


`remove` 删除不存在的元素会报错，所以先用 in 检查。循环遍历的是 to_remove，不是在遍历 courses 时改变 courses 的大小。

**集合运算：**


In [ ]:
a = {1, 2, 3}
b = {3, 4}

print(a | b)  # 并集：{1, 2, 3, 4}
print(a & b)  # 交集：{3}
print(a - b)  # 差集：{1, 2}


这里用 `|` 和 `&`，不要用 `or` 和 `and` 代替。

## 10. 统计每个类别出现的次数


In [18]:
colors = ["red", "blue", "red", "green", "blue", "red"]
unique_colors = list(set(colors))
counts = []

for color in unique_colors:
    counts.append(colors.count(color))

print(unique_colors)
print(counts)


['red', 'green', 'blue']
[3, 1, 2]


假如 unique_colors 的顺序是 red、blue、green，counts 就是 `[3, 2, 1]`。关键是颜色与次数位置对应，不是颜色的固定顺序。

**不用 count 方法的版本：**


In [ ]:
counts = [0] * len(unique_colors)

for color in colors:
    i = unique_colors.index(color)
    counts[i] += 1


每读到一个颜色，找到它对应的计数位置，加 1。

## 11. NumPy：创建数组、切片、复制


In [19]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
print(a * 2)   # [20 40 60 80 100]：逐元素运算
print([1, 2] * 2)  # [1, 2, 1, 2]：列表重复

print(np.zeros(3))        # [0. 0. 0.]
print(np.ones(3) * 0.5)   # [0.5 0.5 0.5]
print(np.arange(0, 5))    # [0 1 2 3 4]：不包含 5
print(np.linspace(0, 5, 3))  # [0. 2.5 5.]：默认包含两端


[ 20  40  60  80 100]
[1, 2, 1, 2]
[0. 0. 0.]
[0.5 0.5 0.5]
[0 1 2 3 4]
[0.  2.5 5. ]


**切片：`a[start:stop:step]`，不包含 stop。**


In [20]:
print(a[1:4])  # [20 30 40]
print(a[-1])   # 50
print(a[-2:])  # [40 50]
print(a[::2])  # [10 30 50]


[20 30 40]
50
[40 50]
[10 30 50]


**基本切片共享数据：**


In [21]:
a = np.array([10, 20, 30])
b = a[1:]
b[0] = 99
print(a)  # [10 99 30]


[10 99 30]


**copy 创建独立数据：**


In [ ]:
a = np.array([10, 20, 30])
b = a[1:].copy()
b[0] = 99
print(a)  # [10 20 30]


`b = a` 对 list 和 array 都不会复制。普通 list 的切片会创建新的外层列表；NumPy 基本切片通常是共享数据的视图。

## 12. 重复实验：每轮都重新生成随机结果


In [ ]:
import random

num_found = 0
num_trials = 100

for trial in range(num_trials):
    roll = random.choice([1, 2, 3, 4, 5, 6])
    if roll == 6:
        num_found += 1

print(num_found)
print(num_found / num_trials)


随机生成在外层循环里面，否则会把同一个结果重复检查 100 次。总成功次数在循环前清零；每次实验独有的 room、found、命中计数等在每轮开头重置。

## 13. 输出字符串：变量放在花括号里


In [ ]:
names = ("Amy", "Ben")
scores = [75, 92]
i = names.index("Ben")

print(f"Old score of {names[i]} is {scores[i]}")
scores[i] = 95
print(f"Current score of {names[i]} is {scores[i]}")


不要硬写名字或数值，用索引取值。f-string 可以直接嵌入数字，不需要 str()。

注意旧值快照不会自动更新：`old_score = scores[i]` 后再修改 scores[i]，old_score 仍保存旧数值。

## 14. 最后自查：你最容易错的地方

- `("Amy")` 是字符串；`("Amy",)` 才是单元素 tuple。
- `t[0:2]` 只取位置 0、1，结果仍是 tuple。
- `t[0] = ...` 不行；`t = t + (...)` 创建新 tuple，可以。
- `for i in receipts` 中 i 是金额，不是 index。
- 处理了 10 个元素，最后一个 index 是 9。
- 独立 if 可能覆盖前面的结果；互斥选项通常用 if/elif/else。
- else 没有条件，且按缩进与对应的 if 对齐。
- 总计数初始化在循环外；每轮实验状态初始化在外层循环内。
- list `.append()`，set `.add()`；别把原地修改方法的 None 返回值赋给原变量。
- 重新运行修改过的 cell；旧输出不代表新代码正确。
- 用确定的边界值测试，再运行随机输入，避免“这次碰巧对了”。
